// Code generated by protoc-gen-go.
// source: op.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	op.proto

It has these top-level messages:
	OpRequest
	OpReply
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type OpRequest struct {
	Op    string `protobuf:"bytes,1,opt,name=op" json:"op,omitempty"`
	Key   string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *OpRequest) Reset()                    { *m = OpRequest{} }
func (m *OpRequest) String() string            { return proto.CompactTextString(m) }
func (*OpRequest) ProtoMessage()               {}
func (*OpRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type OpReply struct {
	Status  int32  `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Msg     string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	ErrCode int32  `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
}

func (m *OpReply) Reset()                    { *m = OpReply{} }
func (m *OpReply) String() string            { return proto.CompactTextString(m) }
func (*OpReply) ProtoMessage()               {}
func (*OpReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*OpRequest)(nil), "pb.OpRequest")
	proto.RegisterType((*OpReply)(nil), "pb.OpReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for RiotGossip service

type RiotGossipClient interface {
	OpRPC(ctx context.Context, in *OpRequest, opts ...grpc.CallOption) (*OpReply, error)
}

type riotGossipClient struct {
	cc *grpc.ClientConn
}

func NewRiotGossipClient(cc *grpc.ClientConn) RiotGossipClient {
	return &riotGossipClient{cc}
}

func (c *riotGossipClient) OpRPC(ctx context.Context, in *OpRequest, opts ...grpc.CallOption) (*OpReply, error) {
	out := new(OpReply)
	err := grpc.Invoke(ctx, "/pb.RiotGossip/OpRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RiotGossip service

type RiotGossipServer interface {
	OpRPC(context.Context, *OpRequest) (*OpReply, error)
}

func RegisterRiotGossipServer(s *grpc.Server, srv RiotGossipServer) {
	s.RegisterService(&_RiotGossip_serviceDesc, srv)
}

func _RiotGossip_OpRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiotGossipServer).OpRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.RiotGossip/OpRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiotGossipServer).OpRPC(ctx, req.(*OpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RiotGossip_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.RiotGossip",
	HandlerType: (*RiotGossipServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpRPC",
			Handler:    _RiotGossip_OpRPC_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x3c, 0x8f, 0xcf, 0xca, 0x82, 0x40,
	0x14, 0x47, 0x3f, 0x95, 0xd1, 0xcf, 0xdb, 0x1f, 0xe2, 0x12, 0x31, 0xb4, 0x0a, 0x21, 0x68, 0xe5,
	0x22, 0x1f, 0xc1, 0x45, 0xab, 0x28, 0xe6, 0x0d, 0x94, 0x86, 0x90, 0x8c, 0x7b, 0x73, 0xc6, 0xc0,
	0xb7, 0x6f, 0xd4, 0x6c, 0x77, 0xce, 0x6f, 0x71, 0x66, 0x2e, 0xfc, 0x13, 0xa7, 0xdc, 0x90, 0x25,
	0xf4, 0xb9, 0x4c, 0x72, 0x88, 0x2f, 0xac, 0xf4, 0xab, 0xd5, 0xc6, 0xe2, 0x12, 0x7c, 0x62, 0xe9,
	0xed, 0xbc, 0x43, 0xac, 0x1c, 0xe1, 0x0a, 0x82, 0x87, 0xee, 0xa4, 0x3f, 0x0c, 0x3d, 0xe2, 0x1a,
	0xc4, 0xbb, 0xa8, 0x5b, 0x2d, 0x03, 0xb7, 0xcd, 0xd5, 0x28, 0xc9, 0x19, 0xa2, 0x3e, 0xc2, 0x75,
	0x87, 0x1b, 0x08, 0x8d, 0x2d, 0x6c, 0x6b, 0x86, 0x8c, 0x50, 0x5f, 0xeb, 0x53, 0x4f, 0x73, 0x9f,
	0x52, 0x0e, 0x51, 0x42, 0xa4, 0x9b, 0x26, 0xa7, 0xdb, 0x18, 0x13, 0x6a, 0xd2, 0x63, 0x06, 0xa0,
	0x2a, 0xb2, 0x27, 0x32, 0xa6, 0x62, 0xdc, 0x83, 0x70, 0xf1, 0x6b, 0x8e, 0x8b, 0x94, 0xcb, 0xf4,
	0xf7, 0xd9, 0xed, 0x6c, 0x52, 0xf7, 0x6c, 0xf2, 0x57, 0x86, 0xc3, 0x4d, 0xd9, 0x27, 0x00, 0x00,
	0xff, 0xff, 0x28, 0x19, 0x61, 0x12, 0xdf, 0x00, 0x00, 0x00,
}
